# Add 'label1' to any changes within 'example' folder or any subfolders
translation/welcome:
  - *.md
  - *.yml
  - *.yaml
  - *.json
  - media/
  - scripts/

# Add 'label2' to any file changes within 'example2' folder
status/PTAL:
  - *.*