{
 "title": "TiDB Cloud Essential Dynamic Tracker (For instances created on or after July 1, 2026)",
 "description": "This Grafana dashboard provides a high-level overview for TiDB Cloud Essential instances created on or after July 1, 2026. ",
 "tags": [
  "tidb",
  "tidb-x",
  "essential-v2"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Instance_name",
    "label": "Instance_name",
    "query": {
     "query": "label_values(tidbcloud_db_row_storage_used_bytes, instance_name)"
    }
   },
   {
    "name": "Instance_id",
    "label": "Instance_id",
    "query": {
     "query": "label_values(tidbcloud_db_row_storage_used_bytes{instance_name=~\"$Instance_name\"}, instance_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_database_time{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(sql_type) (tidbcloud_db_database_time{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_query_per_second{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(type) (tidbcloud_db_query_per_second{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(tidbcloud_db_average_query_duration{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "avg by(sql_type) (tidbcloud_db_average_query_duration{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "Failed Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_failed_queries{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(type) (tidbcloud_db_failed_queries{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Row Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_row_storage_used_bytes{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Row Storage"
    }
   ]
  },
  {
   "title": "Columnar Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_columnar_storage_used_bytes{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Columnar Storage"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_total_connection{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_active_connections{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Disconnection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum by(result) (tidbcloud_db_disconnections{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Command & Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Command Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_command_per_second{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(type) (tidbcloud_db_command_per_second{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queries Using Plan Cache OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_queries_using_plan_cache_ops{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "OPS"
    }
   ]
  },
  {
   "title": "Transaction Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "sum(tidbcloud_db_transaction_per_second{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(type, txn_mode) (tidbcloud_db_transaction_per_second{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{type}}/{{txn_mode}}"
    }
   ]
  },
  { "title": "Request Unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Request Unit",
   "type": "timeseries",
   "description": "The metrics about the request unit cost for all resource groups.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by(resource_group) (tidbcloud_resource_manager_resource_request_unit_total{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{resource_group}}"
    }
   ]
  },
  { "title": "Changefeed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Changefeed Checkpoint Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(changefeed_id) (tidbcloud_changefeed_latency{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{changefeed_id}}"
    }
   ]
  },
  {
   "title": "Changefeed Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "max by(changefeed_id) (tidbcloud_changefeed_status{instance_name=~\"$Instance_name\", instance_id=~\"$Instance_id\"})",
     "legendFormat": "{{changefeed_id}}"
    }
   ]
  }
 ]
}