{
 "title": "TiDB Cloud Overview - Cluster",
 "description": "This dashboard provides a high-level overview of your TiDB clusters.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster_name", "query": { "query": "tidbcloud_db_connections" } }
  ]
 },
 "panels": [
  { "title": "Query Perfromance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Databaset Time",
   "type": "timeseries",
   "description": "database time consumed by SQL statements per second, which are collected by SQL types, such as SELECT, INSERT, and UPDATE.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(cluster_name) (rate(tidbcloud_db_query_duration_seconds_sum{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "database time"
    },
    {
     "expr": "sum by(sql_type) (rate(tidbcloud_db_query_duration_seconds_sum{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "The number of SQL statements executed per second in all TiDB instances, which are collected by SQL types, such as SELECT, INSERT, and UPDATE.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(cluster_name) (rate(tidbcloud_db_queries_total{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "total - QPS"
    },
    {
     "expr": "sum by(sql_type) (rate(tidbcloud_db_queries_total{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "timeseries",
   "description": "The duration from receiving a request from the client to TiDB till TiDB executing the request and returning the result to the client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(cluster_name) (rate(tidbcloud_db_query_duration_seconds_sum{cluster_name=\"$Cluster_name\"}[2m])) / sum by(cluster_name) (rate(tidbcloud_db_query_duration_seconds_count{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(sql_type) (rate(tidbcloud_db_query_duration_seconds_sum{cluster_name=\"$Cluster_name\"}[2m])) / sum by(sql_type) (rate(tidbcloud_db_query_duration_seconds_count{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "P99 Query Duration",
   "type": "timeseries",
   "description": "The duration from receiving a request from the client to TiDB till TiDB executing the request and returning the result to the client.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster_name) (rate(tidbcloud_db_query_duration_seconds_bucket{cluster_name=\"$Cluster_name\"}[2m])))",
     "legendFormat": "All Query P99"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, sql_type) (rate(tidbcloud_db_query_duration_seconds_bucket{cluster_name=\"$Cluster_name\"}[2m])))",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "Failed Queries",
   "type": "timeseries",
   "description": "The statistics of error types (such as syntax errors and primary key conflicts) according to the SQL statement execution errors per minute on each TiDB instance. It contains the module in which an error occurs and the error code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(type) (rate(tidbcloud_db_failed_queries_total{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Current number of connections in your TiDB server\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "tidbcloud_db_connections{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  { "title": "Server - TiDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "TiDB CPU",
   "type": "timeseries",
   "description": "The statistics of CPU usage of each TiDB instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(exported_instance) (rate(tidbcloud_node_cpu_seconds_total{cluster_name=\"$Cluster_name\", component=\"tidb\"}[2m]))",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_cpu_capacity_cores{cluster_name=\"$Cluster_name\", component=\"tidb\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TiDB Memory",
   "type": "timeseries",
   "description": "The memory usage statistics of each TiDB instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "tidbcloud_node_memory_used_bytes{cluster_name=\"$Cluster_name\", component=\"tidb\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_memory_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tidb\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  { "title": "Server - TiKV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "TiKV CPU",
   "type": "timeseries",
   "description": "The statistics of CPU usage of each TiKV instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(exported_instance) (rate(tidbcloud_node_cpu_seconds_total{cluster_name=\"$Cluster_name\", component=\"tikv\"}[2m]))",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_cpu_capacity_cores{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TiKV Memory",
   "type": "timeseries",
   "description": "The memory usage statistics of each TiKV instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "tidbcloud_node_memory_used_bytes{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_memory_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TiKV Storage",
   "type": "timeseries",
   "description": "The storage size per TiKV instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "tidbcloud_node_storage_used_bytes{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_storage_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  { "title": "Server - TiFlash", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "TiFlash CPU",
   "type": "timeseries",
   "description": "The statistics of CPU usage of each TiFlash instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(exported_instance) (rate(tidbcloud_node_cpu_seconds_total{cluster_name=\"$Cluster_name\", component=\"tiflash\"}[2m]))",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_cpu_capacity_cores{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TiFlash Memory",
   "type": "timeseries",
   "description": "The memory usage statistics of each TiKV instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "tidbcloud_node_memory_used_bytes{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_memory_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TiFlash Storage",
   "type": "timeseries",
   "description": "The storage size per TiFlash instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "tidbcloud_node_storage_used_bytes{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_storage_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  }
 ]
}