{
 "title": "TiDB Cloud Overview - Cluster",
 "description": "This dashboard provides a high-level overview of your TiDB clusters.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cluster_name", "query": { "query": "tidbcloud_db_connections" } }
  ]
 },
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tidbcloud_component_uptime{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Query Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Database Time",
   "type": "timeseries",
   "description": "database time consumed by SQL statements per second, which is collected by SQL types, such as SELECT, INSERT, and UPDATE.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(cluster_name) (rate(tidbcloud_db_query_duration_seconds_sum{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "database time"
    },
    {
     "expr": "sum by(sql_type) (rate(tidbcloud_db_query_duration_seconds_sum{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "The number of SQL statements executed per second in all TiDB instances, which is collected by SQL types, such as SELECT, INSERT, and UPDATE.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(cluster_name) (rate(tidbcloud_db_queries_total{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "total - QPS"
    },
    {
     "expr": "sum by(sql_type) (rate(tidbcloud_db_queries_total{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "timeseries",
   "description": "The duration from receiving a request from the client to TiDB till TiDB executing the request and returning the result to the client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(cluster_name) (rate(tidbcloud_db_query_duration_seconds_sum{cluster_name=\"$Cluster_name\"}[2m])) / sum by(cluster_name) (rate(tidbcloud_db_query_duration_seconds_count{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(sql_type) (rate(tidbcloud_db_query_duration_seconds_sum{cluster_name=\"$Cluster_name\"}[2m])) / sum by(sql_type) (rate(tidbcloud_db_query_duration_seconds_count{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "P99 Query Duration",
   "type": "timeseries",
   "description": "The duration from receiving a request from the client to TiDB till TiDB executing the request and returning the result to the client.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster_name) (rate(tidbcloud_db_query_duration_seconds_bucket{cluster_name=\"$Cluster_name\"}[2m])))",
     "legendFormat": "All Query P99"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, sql_type) (rate(tidbcloud_db_query_duration_seconds_bucket{cluster_name=\"$Cluster_name\"}[2m])))",
     "legendFormat": "{{sql_type}}"
    }
   ]
  },
  {
   "title": "Failed Queries",
   "type": "timeseries",
   "description": "The statistics of error types (such as syntax errors and primary key conflicts) according to the SQL statement execution errors per minute on each TiDB instance. It contains the module in which an error occurs and the error code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(type) (rate(tidbcloud_db_failed_queries_total{cluster_name=\"$Cluster_name\"}[2m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Current number of connections in your TiDB server\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "tidbcloud_db_connections{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Disk Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tidbcloud_disk_read_latency{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{exported_instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tidbcloud_disk_write_latency{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{exported_instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Average TiDB KV Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tidbcloud_kv_request_duration{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "ChangeFeed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "tidbcloud_changefeed_latency", "legendFormat": "{{changefeed_id}}" }
   ]
  },
  {
   "title": "Replica rows Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "tidbcloud_changefeed_Replica_rows",
     "legendFormat": "{{changefeed_id}}"
    }
   ]
  },
  {
   "title": "Changefeed Resolved Ts Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tidbcloud_ticdc_owner_resolved_ts_lag",
     "legendFormat": "{{changefeed_id}}"
    }
   ]
  },
  {
   "title": "Changefeed Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(tidbcloud_changefeed_status{cluster_name=\"$Cluster_name\"}) by (changefeed_id)",
     "legendFormat": "{{changefeed_id}}"
    }
   ]
  },
  { "title": "Server - TiDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "TiDB CPU",
   "type": "timeseries",
   "description": "The statistics of CPU usage of each TiDB instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(exported_instance) (rate(tidbcloud_node_cpu_seconds_total{cluster_name=\"$Cluster_name\", component=\"tidb\"}[2m]))",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_cpu_capacity_cores{cluster_name=\"$Cluster_name\", component=\"tidb\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TiDB Memory",
   "type": "timeseries",
   "description": "The memory usage statistics of each TiDB instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "tidbcloud_node_memory_used_bytes{cluster_name=\"$Cluster_name\", component=\"tidb\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_memory_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tidb\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  { "title": "Server - TiKV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "TiKV CPU",
   "type": "timeseries",
   "description": "The statistics of CPU usage of each TiKV instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(exported_instance) (rate(tidbcloud_node_cpu_seconds_total{cluster_name=\"$Cluster_name\", component=\"tikv\"}[2m]))",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_cpu_capacity_cores{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TiKV Memory",
   "type": "timeseries",
   "description": "The memory usage statistics of each TiKV instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "tidbcloud_node_memory_used_bytes{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_memory_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TiKV Storage",
   "type": "timeseries",
   "description": "The storage size per TiKV instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "tidbcloud_node_storage_used_bytes{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "tidbcloud_node_storage_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "limit-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "TiKV Available Storage",
   "type": "timeseries",
   "description": "The available storage size per TiKV instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "tidbcloud_node_storage_available_bytes{cluster_name=\"$Cluster_name\", component=\"tikv\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Server - TiFlash",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "TiFlash CPU",
     "type": "timeseries",
     "description": "The statistics of CPU usage of each TiFlash instance.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(exported_instance) (rate(tidbcloud_node_cpu_seconds_total{cluster_name=\"$Cluster_name\", component=\"tiflash\"}[2m]))",
       "legendFormat": "{{exported_instance}}"
      },
      {
       "expr": "tidbcloud_node_cpu_capacity_cores{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
       "legendFormat": "limit-{{exported_instance}}"
      }
     ]
    },
    {
     "title": "TiFlash Memory",
     "type": "timeseries",
     "description": "The memory usage statistics of each TiKV instance.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "tidbcloud_node_memory_used_bytes{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
       "legendFormat": "{{exported_instance}}"
      },
      {
       "expr": "tidbcloud_node_memory_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
       "legendFormat": "limit-{{exported_instance}}"
      }
     ]
    },
    {
     "title": "TiFlash Storage",
     "type": "timeseries",
     "description": "The storage size per TiFlash instance.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "tidbcloud_node_storage_used_bytes{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
       "legendFormat": "{{exported_instance}}"
      },
      {
       "expr": "tidbcloud_node_storage_capacity_bytes{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
       "legendFormat": "limit-{{exported_instance}}"
      }
     ]
    },
    {
     "title": "TiFlash Available Storage",
     "type": "timeseries",
     "description": "The storage size per TiFlash instance.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "tidbcloud_node_storage_available_bytes{cluster_name=\"$Cluster_name\", component=\"tiflash\"}",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Resource Unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Resource Group RU",
   "type": "timeseries",
   "description": "The metrics about the request unit cost for all resource groups.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum (tidbcloud_resource_manager_resource_unit_read_request_unit{cluster_name=\"$Cluster_name\"}) by (resource_group) + sum (tidbcloud_resource_manager_resource_unit_write_request_unit{cluster_name=\"$Cluster_name\"}) by (resource_group)",
     "legendFormat": "{{resource_group}}"
    },
    {
     "expr": "sum (tidbcloud_resource_manager_resource_unit_read_request_unit{cluster_name=\"$Cluster_name\"})  + sum (tidbcloud_resource_manager_resource_unit_write_request_unit{cluster_name=\"$Cluster_name\"}) ",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "DM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "DM Relay Read Error Count",
   "type": "timeseries",
   "description": "DM Relay Read Error Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "tidbcloud_dm_relay_read_error_count{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{cluster_name}} ---> {{job}}"
    }
   ]
  },
  {
   "title": "DM Syncer Replication Lag Bucket",
   "type": "timeseries",
   "description": "DM Syncer Replication Lag Bucket",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tidbcloud_dm_syncer_replication_lag_bucket{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{cluster_name}} ---> {{job}} ---> {{task}}"
    }
   ]
  },
  {
   "title": "DM Syncer Replication Lag Gauge",
   "type": "timeseries",
   "description": "DM Syncer Replication Lag Gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tidbcloud_dm_syncer_replication_lag_gauge{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{cluster_name}} ---> {{job}} ---> {{task}}"
    }
   ]
  },
  {
   "title": "DM Task State",
   "type": "timeseries",
   "description": "DM Task State",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tidbcloud_dm_task_status{cluster_name=\"$Cluster_name\"}",
     "legendFormat": "{{cluster_name}} ---> {{job}} ---> {{task}}"
    }
   ]
  }
 ]
}