#!/bin/bash

set -e
# test passed in pandoc 1.19.1

# Fedora: dnf install wqy-microhei-fonts
MAINFONT="WenQuanYi Micro Hei"
MONOFONT="WenQuanYi Micro Hei Mono"

# MAINFONT="Tsentsiu Sans HG"
# MONOFONT="Tsentsiu Sans Console HG"

#_version_tag="$(date '+%Y%m%d').$(git rev-parse --short HEAD)"
_version_tag="$(date '+%Y%m%d')"

# default version: `pandoc --latex-engine=xelatex doc.md -s -o output2.pdf`
# used to debug template setting error

# Note that doc.md must first be generated by ./scripts/merge_by_toc.py

pandoc \
	-s \
	-N \
	--toc \
	-f markdown+smart \
	--pdf-engine=xelatex \
	--template=templates/template.tex \
	--columns=120 \
	--listings \
	-V title="TiDB Documentation" \
	-V author="PingCAP Inc." \
	-V date="${_version_tag}" \
	-V CJKmainfont="${MAINFONT}" \
	-V fontsize=12pt \
	-V geometry:margin=1in \
	-V include-after="\\input{templates/copyright.tex}" \
	-o "output.pdf" \
	"doc.md"
