name: Trigger docs site update

on:
  push:
    branches:
<<<<<<< HEAD
      - release-5.1
=======
      - master
      - release-*
>>>>>>> 8e6ae6082 (chore: update dispatch for latest docs site (#7118))

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Extract sha
      id: extract
      shell: bash
      run: |
        echo "::set-output name=sha::$(sha=${{ github.sha }}; echo ${sha:0:6})"

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.PR_TRIGGER_BUILD_TOKEN }}
          repository: pingcap/website-docs
          event-type: ${{ github.repository }}/${{ github.ref_name }}-${{ steps.extract.outputs.sha }}
          client-payload: '{ "repo": "${{ github.repository }}", "ref": "${{ github.ref_name }}", "sha": "${{ github.sha }}" }'
