name: Trigger docs site update

on:
  push:
    branches:
<<<<<<< HEAD
      #- master
      #- release-*
      - release-2.1
      - release-3.*
      - release-4.0
      - release-5.*
      - release-6.0
=======
      - master
      - release-*
      - i18n-ja-release-5.4
>>>>>>> 5b00e1013 (trigger dispatch (#8930))

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Extract sha
      id: extract
      shell: bash
      run: |
        echo "::set-output name=sha::$(sha=${{ github.sha }}; echo ${sha:0:6})"

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.PR_TRIGGER_BUILD_TOKEN }}
          repository: pingcap/website-docs
          event-type: ${{ github.repository }}/${{ github.ref_name }}-${{ steps.extract.outputs.sha }}
          client-payload: '{ "repo": "${{ github.repository }}", "ref": "${{ github.ref_name }}", "sha": "${{ github.sha }}" }'
