name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Git
      run: git fetch origin ${{ github.event.pull_request.head.ref }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Label Pull Request
      uses: actions/labeler@v4
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        configuration-path: .github/labeler.yml
        sync-labels: true
        dot: true
