name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Exclude Path
        run: |
          curl https://raw.githubusercontent.com/Oreoxmt/docs/ci/add-lycheeignore/.github/exclude-links.txt --output .lycheeignore

      - name: Check Links Exclude GitHub
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          # For parameter description, see https://github.com/lycheeverse/lychee#commandline-parameters
          args: -E --exclude-mail -v -i -n -t 45 --exclude github\.com -- **/*.md
          output: exclude-out.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Check Links Include GitHub
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          # For parameter description, see https://github.com/lycheeverse/lychee#commandline-parameters
          args: -E --exclude-mail -v -i -n -t 45 --max-concurrency 1 --exclude *.com --include github\.com -- **/*.md
          output: include-out.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Get Output
        run: |
          cat exclude-out.md include-out.md > out.md
          cat out.md

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Broken Link Detected
          content-filepath: out.md
          assignees: TomShawn

#      - name: Fail if there were link errors
#        run: exit ${{ steps.lychee.outputs.exit_code }}
