name: Links (Fail Fast)

on:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Exclude Path
        run: |
          curl https://raw.githubusercontent.com/pingcap/docs/master/.lycheeignore --output .lycheeignore

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          fail: true
          # Accept 429 for now due to github rate limit.
          # See https://github.com/lycheeverse/lychee/issues/634
          args: -E --exclude-mail -v -i -n -t 45 -a 429 -- **/*.md *.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}