name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Exclude Path
        run: |
          curl https://github.com/Oreoxmt/docs/blob/ci/add-lycheeignore/.github/exclude-links.txt --output .lycheeignore

      - name: Check Links Exclude GitHub
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          # For parameter description, see https://github.com/lycheeverse/lychee#commandline-parameters
          args: --output ./lychee/exclude-out.md -E --exclude-mail -v -i -n -t 45 --exclude github.com -- **/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Check Links Include GitHub
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          # For parameter description, see https://github.com/lycheeverse/lychee#commandline-parameters
          args: -E --exclude-mail -v -i -n -t 45 --max-concurrency 1 --include github.com --output ./lychee/include-out.md -- **/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Get Output
        run: |
          cat ./lychee/exclude-out.md ./lychee/include-out.md > ./lychee/out.md
          cat ./lychee/out.md

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Broken Link Detected
          content-filepath: ./lychee/out.md
          assignees: TomShawn

#      - name: Fail if there were link errors
#        run: exit ${{ steps.lychee.outputs.exit_code }}
