name: PR Creation Test

on:
  workflow_dispatch:

env:
  CN_CLOUD_BRANCH: i18n-zh-release-8.1

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Download docs repo and specified branch
        with:
          ref: "${{ env.CN_CLOUD_BRANCH }}"
          path: "docs"

      - name: Set build ID
        id: build_id
        run: echo "::set-output name=id::$(date +%s)"

      - name: Create test file
        run: |
          cd docs
          echo "# Test PR Creation" > test-pr-creation.md
          echo "This is a test file for PR creation workflow." >> test-pr-creation.md
          echo "Created at: $(date)" >> test-pr-creation.md

      - name: Git commit and push
        id: git_commit
        run: |
          cd docs
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b pr-test/${{ steps.build_id.outputs.id }}
          git add .
          if git status | grep -q "Changes to be committed"
          then
            git commit -m "test: Add test file for PR creation workflow"
            git push origin pr-test/${{ steps.build_id.outputs.id }}
            echo "::set-output name=committed::1"
          else
            echo "No changes detected, skipped"
          fi

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        if: steps.git_commit.outputs.committed == 1
        with:
          token: ${{ github.token }}
          branch: pr-test/${{ steps.build_id.outputs.id }}
          base: ${{ env.CN_CLOUD_BRANCH }}
          title: "test: PR Creation Test ${{ steps.build_id.outputs.id }}"
          body: |
            ### What is changed, added or deleted? (Required)

            This is a test PR for the PR creation workflow.

            ### Which TiDB version(s) do your changes apply to? (Required)

            <!-- Fill in "x" in [] to tick the checkbox below.-->

            **Tips for choosing the affected version(s):**

            By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

            For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

            - [x] ${{ env.CN_CLOUD_BRANCH }}

            ### What is the related PR or file link(s)?

            <!--Reference link(s) will help reviewers review your PR quickly.-->

            - This is a test PR
            - Other reference link(s):

            ### Do your changes match any of the following descriptions?

            - [ ] Delete files
            - [ ] Change aliases
            - [ ] Need modification after applied to another branch <!-- If yes, please comment "/label version-specific-changes-required" below to trigger the bot to add the label. -->
            - [ ] Might cause conflicts after applied to another branch
          delete-branch: true
